CREATE TABLE "aw-web_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "aw-web_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "aw-web_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"sub" varchar(255) NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"image" varchar(255),
	CONSTRAINT "aw-web_user_sub_unique" UNIQUE("sub")
);
--> statement-breakpoint
ALTER TABLE "aw-web_post" ADD CONSTRAINT "aw-web_post_createdById_aw-web_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."aw-web_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "aw-web_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "aw-web_post" USING btree ("name");