name: DB Migrate

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  migrate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.SCRUM_DATABASE_URL }}
      AUTH_DISCORD_ID: ${{ secrets.AUTH_DISCORD_ID }}
      AUTH_DISCORD_SECRET: ${{ secrets.AUTH_DISCORD_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run DB migrations
        run: pnpm db:migrate

      - name: Run DB seed
        run: pnpm db:seed
